### ISSUE TITLE
CameraInput does not work with older versions v4l-utils 

### ISSUE THREAD

**Issue by IronKai123** [opensight-cv/opensight#3]
Camera used - Logitech HD Pro Webcam C920 (h264 and MJPEG Capable)

Drive link to the terminal i/o -> https://drive.google.com/drive/folders/1gkdJJtxD8x_nj3azOCujJFEbB3Y4NXah?usp=sharing 

Even though our camera was connected, Opensight could not detect the program as running. A test python program was run, testing if the camera was connected. The test program did provide video feed from the camera. After multiple trials, it was revealed that Opensight had a problem. I hope this can be fixed in the future.

**Comment by 132ikl** [comment]
Output of issuer's `v4l2-ctl --list-formats-ext`: https://fs.ikl.sh/4e3ib65j.file

**Comment by 132ikl** [comment]
Cause of the issue is that v4l2-ctl outputs the format information on current version and the version IronKai123 is on. @IronKai123 I recommend doing the following to install the current version of v4l-utils if you distribution does not package the latest version:

First, uninstall your disto-provided v4l-utils (eg. `sudo apt remove v4l-utils`)
then, run these commands:
```
wget https://linuxtv.org/downloads/v4l-utils/v4l-utils-1.16.7.tar.bz2
tar xvfj v4l-utils-1.16.7.tar.bz2
cd v4l-utils-1.16.7
./configure
make
sudo make install
```
